export const dataList = [
  {
    id: 1,
    title: '2 POKOJE Z WIDOKIEM NA BASEN W KOMPLEKSIE JULIA FAMILY',
    serviceTime: '45-60min',
    deliveryFee: 3.44,
    category: 'place',
    cuisine: 'american',
    rating: 5,
    price: 68500,
    coverSrc: '/images/apartment-1.jpeg',
  },
  {
    id: 2,
    title: 'STUDIO Z WIDOKIEM NA MORZE NA KOMPLEKSIE CAŁOROCZNYM FITNESS I SPA',
    serviceTime: '15-20min',
    deliveryFee: 4.94,
    category: 'place',
    cuisine: 'italian',
    rating: 4,
    price: 38650,
    coverSrc: '/images/apartment-2.jpeg',
  },
  {
    id: 3,
    title: 'ELEGANCKIE STUDIO NA 5* KOMPLEKSIE 500M OD PLAŻY W CENTRUM SŁONECZNEGO BRZEGU',
    serviceTime: '30-22min',
    deliveryFee: 4.94,
    price: 32500,
    coverSrc: '/images/apartment-3.jpeg',
  },
  {
    id: 4,
    title: 'STYLOWO URZĄDZONE 2 POKOJE Z WIDOKIEM NA BASEN NA KOMPLEKSIE PREMIUM DAWN PARK',
    serviceTime: '10-18min',
    deliveryFee: 2.14,
    price: 41000,
    coverSrc: '/images/apartment-4.jpeg',
  },
  {
    id: 5,
    title: '2 POKOJE W PIERWSZEJ LINII BRZEGOWEJ W MALOWNICZEJ MIEJSCOWOŚCI ELENITE',
    serviceTime: '25-30min',
    deliveryFee: 6.79,
    price: 47999,
    coverSrc: '/images/apartment-5.jpeg',
  },
  {
    id: 6,
    title: 'STUDIO Z CZĘŚCIOWYM WIDOKIEM NA MORZE I BASEN NA 1 LINII BRZEGOWEJ',
    serviceTime: '5-15min',
    deliveryFee: 2.87,
    price: 45950,
    coverSrc: '/images/apartment-6.jpeg',
  },
  {
    id: 7,
    title: 'WYKWINTNE APARTAMENTY Z WIDOKIEM NA MORZE NA SPRZEDAŻ W TURKLER',
    serviceTime: '50-65min',
    deliveryFee: 8.5,
    price: 68500,
    coverSrc: '/images/apartment-7.jpeg',
  },
  {
    id: 8,
    title: 'PRZYTULNE APARTAMENTY Z HOTELEM CONCEPT W DOGODNEJ LOKALIZACJI W STAMBULE',
    serviceTime: '10-15min',
    deliveryFee: 1.8,
    price: 38650,
    coverSrc: '/images/apartment-8.jpeg',
  },
  {
    id: 9,
    title: 'NA SPRZEDAŻ APARTAMENT ALANYA OBA',
    serviceTime: '12-18min',
    deliveryFee: 3.33,
    price: 32500,
    coverSrc: '/images/apartment-9.jpeg',
  },
  {
    id: 10,
    title: 'NOWOCZESNE APARTAMENTY Z WIDOKIEM NA MORZE WE WSPANIAŁYM TOSMUR\n',
    serviceTime: '30-38min',
    deliveryFee: 1.9,
    price: 41000,
    coverSrc: '/images/apartment-10.jpeg',
  },
  {
    id: 11,
    title: 'APARTMENTY W POŻĄDANEJ LOKALIZACJI W SŁYNNYM REGIONIE OBA\n',
    serviceTime: '16-20min',
    deliveryFee: 4.1,
    price: 47999,
    coverSrc: '/images/apartment-11.jpeg',
  },
  {
    id: 12,
    title: 'APARTAMENTY KLASY PREMIUM W POPULARNYM MAHMUTLAR\n',
    serviceTime: '24-30min',
    deliveryFee: 1.5,
    price: 45950,
    coverSrc: '/images/apartment-12.jpeg',
  },
];
